services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    env_file:
      - .env
    volumes:
      # Mounts the project directory into the container at /app
      - ./frontend/:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - .env
    volumes:
      - ./backend/:/app
  
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 64mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
     - type: tmpfs
       target: /dev/shm
       tmpfs:
         size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}